---
# configuration for GitHub Actions
name: rerobots CLI tests
on:
    push:
    pull_request:
jobs:
    build:
        name: Build
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - run: |
                rustup toolchain install nightly --profile minimal
                rustup component add --toolchain nightly rustfmt
            - run: rustup toolchain install stable --profile minimal
            - uses: Swatinem/rust-cache@v2
            - name: Lint
              run: |
                cargo +nightly fmt --check
                cargo check
                cargo clippy --tests -- -D clippy::all
            - name: Run tests
              run: |
                cargo test
