---
# configuration for GitHub Actions
name: rerobots CLI tests
on:
    push:
    pull_request:
jobs:
    build:
        name: Build
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [
                    ubuntu-22.04,
                    macos-latest,
                    windows-latest,
                ]
        steps:
            - uses: actions/checkout@v4
            - run: rustup toolchain install stable --profile minimal
            - uses: Swatinem/rust-cache@v2
            - name: Lint
              if: runner.os != 'Windows'
              run: |
                cargo fmt --check
                cargo check
                cargo clippy --tests -- -D clippy::all
            - name: Run tests
              run: |
                cargo test
